---
title:    |
    | Should I Airbnb my Property:    
    | Executive Summary
    |   
    |  

author:
- Andy Krause
- '&'
- Gideon Aschwanden
- University of Melbourne
date: "March 17, 2017"
output:
  pdf_document: default
  html_document: default
---

This research sets out to test under which conditions, if any, a short-term leasing strategy (Airbnb) generates more net revenue than a traditional long-term approach.  Our data and analysis focus on the Melbourne metropolitan region.  To make comparisons between short- and long-term markets we analyze observed short-term and imputed long-term revenues for a particular scenario where a property owner purchases a property on September 1 2015 and makes a decision between long- or short-term rental for the next 12 months.  

Our exploratory analysis shows that the univariate distribution of observed short-term revenues (from Airbnb) is much more variable than observed long-term revenue from the traditional rental market.  Most Airbnb'd properties makes less but some make more, much more. To form a better comparison of revenues between similar properties, we impute likely long-term revenues for the short-term properties using a model based on the long-term rental market observations. Over the entire market, we find that 27.7\% of the Airbnb properties did collect more revenue than they would likely do so with a long-term leasing strategy.  The probability of preference for a short-term strategy, however, is not equal for all types of properties.  More specifically, we find that short-term preference is higher in:

1. Apartments versus homes
2. Smaller versus larger properties
3. Properties in the city-core (central 18 suburbs)
4. Rural areas as opposed to suburban (but not versus city properties)

We also find the following host behaviors or policies result in higher probability of short-term preference:

1. More allowed guests per bedroom
2. Shorter minimum stays
3. More strict cancellation policies

Overall, we find that, indeed, some properties may generate more revenue under a short-term approach than in a long-term strategy. The probability of acheiving short-term preference is highest for small apartments in the city-core with low minimum stays, strict cancellation policies and a high number of guests per bedroom. However, even within the core city apartment market an owner must achieve a nightly rate and an overall occupancy rate both above the median in order to reach an equal probability of short-term preference.  In other words, there is solid competition in this market and short-term preference depends on proper pricing, high occupancy and host policies.  

Sensitivity tests suggest that using a measure of potential revenue (ignoring effect of blocked days) equates to a higher baseline probability for short-term preference, however, the direction and magnitude of influence of the various structural, location and policy factors on determining preference remains similar between the two revenue types (actual or potential).  Additional sensitivity tests also show that, based on availability schedules, not all users appear to be using the Airbnb portal for the purpose of profit maximization.  When we limit the sample to those hosts who appear to be attempting to maximize revenues we find that the baseline short-term preference rate is much higher, slightly greater than 50\%, but that, like the use of potential revenue, the imnpacts of the various structural, location and policy factors remain similar to the analyses using the entire market.  

In sum, slightly more than one in four Airbnb'd units is making more than they would on the long-term market.  If we look only at those hosts who are aggressively chasing revenue this proportion increases to just over 50\%.  In both instances, the cases of short-term preference are not evenly distributed but focused on small apartments in the city center leased by hosts with liberal use but strict cancellation policies. It is no surprise given these results that inner city apartments make up a large proportion of the Airbnb market in Melbourne.  The market appears aware, to some extent, of the profitability of this property type under a short-term approach.  It will be interesting to examine the market moving forward to see if supply in these area has already or will eventually outstrip demand.  

Finally, all code used to create this analysis can be found at:  [www.github.com/andykrause/airbnbMelbourne](https://www.github.com/andykrause/airbnbMelbourne).  An interactive website that allows for deeper exploration of the results is available at: [https://andykrause.shinyapps.io/ShouldIAirbnb](https://andykrause.shinyapps.io/ShouldIAirbnb).

